Repository knative-extensions/net-istio, pull requests merged in 2020-04, with the labels that each got.

#59 Allow trailing dot for gateway service URL
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/config/istio_test.go
Labels: approved, cla: yes, lgtm, size/S

#64 Point release to v0.14 release branch of knative/serving
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/third_party/istio-1.4-latest
  vendor/knative.dev/serving/third_party/istio-1.5-latest
  vendor/knative.dev/serving/third_party/istio-stable
Labels: approved, cla: yes, lgtm, size/M

#65 Explicitly freeze test-infra
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/XS

#66 Run net-istio as non-root
  .ko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#61 Add helper functions for handling wildcard certificate
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
Labels: approved, cla: yes, lgtm, size/L

#67 Coalesce the Gateway.spec.servers[] with the same port and protocol
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
Labels: approved, cla: yes, lgtm, size/M

#69 ingress: Skip gateway servers with mutual TLS configured
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#70 Fix some logging around istio ingress
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#71 Also delete VirtualServices created before Knative 0.12
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, size/L

#74 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE
  vendor/knative.dev/pkg/injection/context.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/prober/prober.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/resources/endpoints.go
  vendor/knative.dev/serving/pkg/resources/pods.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#78 Pin back to knative/{serving,pkg}@release-0.14.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/network/stats.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/pkg/network/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/knative.dev/serving/pkg/resources/doc.go
  vendor/knative.dev/serving/pkg/resources/endpoints.go
  vendor/knative.dev/serving/pkg/resources/pods.go
  vendor/knative.dev/serving/pkg/resources/scale.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/knative.dev/serving/test/apicoverage.sh
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/e2e_constants.go
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/knative.dev/serving/test/presubmit-tests.sh
  vendor/knative.dev/serving/test/system.go
  vendor/knative.dev/serving/test/test_images/grpc-ping/main.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/args.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/cgroup.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/env.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/file.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/mount.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/request.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/runtime.go
  vendor/knative.dev/serving/test/test_images/runtime/main.go
  vendor/knative.dev/serving/test/types/runtime.go
  vendor/knative.dev/serving/test/util.go
  vendor/knative.dev/serving/test/v1/configuration.go
  vendor/knative.dev/serving/test/v1/route.go
  vendor/knative.dev/serving/test/v1/service.go
  vendor/knative.dev/serving/test/v1alpha1/configuration.go
  vendor/knative.dev/serving/test/v1alpha1/route.go
  vendor/knative.dev/serving/test/v1alpha1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#79 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/github.com/google/licenseclassifier/.travis.yml
  vendor/github.com/google/licenseclassifier/classifier.go
  vendor/github.com/google/licenseclassifier/file_system_resources.go
  vendor/github.com/google/licenseclassifier/go.mod
  vendor/github.com/google/licenseclassifier/go.sum
  vendor/github.com/google/licenseclassifier/license_type.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#81 Update to get latest conformance/ingress tests.
  go.mod
  go.sum
  hack/tools.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/serving/test/conformance/ingress/README.md
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
