Repository knative-extensions/net-istio, pull requests merged in 2020-05, with the labels that each got.

#82 Pull latest ingress conformance tests.
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/route.go
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#83 Pickup fixed conformance/ingress tests
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#84 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/service_validation.go
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/e2e/scale.go
  vendor/knative.dev/serving/test/e2e/websocket.go
  vendor/knative.dev/serving/test/test_images/grpc-ping/main.go
  vendor/knative.dev/serving/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/serving/test/test_images/runtime/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#85 Wait for static IP address to be up and reachable in test.
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/M

#88 Only set VirtualService retry field for when KIngress has retry setting.
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, lgtm, size/M

#87 Use wait function from knative.dev/test-infra
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S

#93 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#92 Add ingress-provider label to webhook
  config/500-mutating-webhook.yaml
  config/500-validating-webhook.yaml
  config/500-webhook-secret.yaml
  config/webhook-deployment.yaml
  config/webhook-service.yaml
Labels: approved, cla: yes, lgtm, size/XS

#96 Fix presubmit tests to use vendor and have all images.
  go.mod
  hack/tools.go
  vendor/knative.dev/serving/test/test_images/helloworld/README.md
  vendor/knative.dev/serving/test/test_images/helloworld/helloworld.go
  vendor/knative.dev/serving/test/test_images/helloworld/helloworld.yaml
  vendor/knative.dev/serving/test/test_images/helloworld/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#99 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#100 Try to make ingress conformance tests run again
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#103 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/gc/config.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/test/adding_tests.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#104 Fix update-codegen for the post-go-mod world.
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/XS

#105 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#106 [RELEASE] Pin knative.dev/{pkg,test-infra} to release-0.15
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#102 Add Gateway related helper functions for generating Gateway for wildcard certificate
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
Labels: approved, cla: yes, lgtm, size/L

#107 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#108 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#109 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#111 [RELEASE] Pin serving to 0.15.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#112 [POST-RELEASE] Track master branches again.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#110 Move GenerateCertifiate into a util file so it could reused in the following PR
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/secret_test.go
  pkg/reconciler/ingress/resources/util.go
Labels: approved, cla: yes, lgtm, size/L

#113 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/service.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#114 Allow unknown fields in VirtualService and Gateway deserialization
  cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/XS

#115 Add config-features.yaml into test/config.
  test/config/config-features.yaml
Labels: approved, cla: yes, lgtm, size/M

#117 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/network/stats.go
  vendor/knative.dev/serving/test/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#116 Backport "Coalescing the Gateway.spec.servers[]" #67 to the 0.14 branch
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/serving/test/test_images/helloworld/README.md
  vendor/knative.dev/serving/test/test_images/helloworld/helloworld.go
  vendor/knative.dev/serving/test/test_images/helloworld/helloworld.yaml
  vendor/knative.dev/serving/test/test_images/helloworld/service.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#120 [RELEASE-0.15] Backport "Allow unknown fields. (#114)"
  cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/XS

#122 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/test/test_images/httpproxy/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#125 Add dummy.go to make config/ importable
  config/dummy.go
Labels: approved, cla: yes, lgtm, size/S
