Repository knative-extensions/net-istio, pull requests merged in 2020-09, with the labels that each got.

#260 Add global.mtls.auto false explicitly in values-local.yaml and values-lean.yaml
  third_party/istio-1.5.7-helm/istio-ci-no-mesh.yaml
  third_party/istio-1.5.7-helm/istio-minimal.yaml
  third_party/istio-1.5.7-helm/values-lean.yaml
  third_party/istio-1.5.7-helm/values-local.yaml
Labels: approved, cla: yes, lgtm, size/XL

#264 Fix the deletes for the new pkg update
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, size/XS

#266 Add support for -short
  test/conformance/ingress_test.go
Labels: approved, cla: yes, lgtm, size/XS

#267 Fix go vet issues
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, lgtm, size/M

#268 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#271 Add linting config and fix issues.
  .golangci.yaml
  pkg/reconciler/accessor/errors.go
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, size/S

#270 Fix the incorrect unit test when auto TLS is enabled
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, size/M

#263 Update dependencies.
  go.mod
  go.sum
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#273 Update dependencies.
  go.mod
  go.sum
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#274 [master] Update GitHub Actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#275 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#281 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#283 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#284 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#282 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#286 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#280 Set Istio latest to Istio 1.7.1.
  third_party/istio-latest
  third_party/istio-latest/README.md
  third_party/istio-latest/install-istio.sh
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-minimal.yaml
  third_party/istio-stable
  third_party/istio-stable/download-istio.sh
  third_party/istio-stable/drain-seconds.yaml.patch
  third_party/istio-stable/install-istio.sh
  third_party/istio-stable/istio-ci-mesh.yaml
  third_party/istio-stable/istio-ci-no-mesh.yaml
  third_party/istio-stable/istio-crds.yaml
  third_party/istio-stable/istio-knative-extras.yaml
  third_party/istio-stable/istio-minimal.yaml
  third_party/istio-stable/namespace.yaml.patch
  third_party/istio-stable/values-extras.yaml
  third_party/istio-stable/values-lean.yaml
  third_party/istio-stable/values-local.yaml
  third_party/istio-stable/values.yaml
Labels: approved, cla: yes, lgtm, size/M

#288 Include HEAD commit hash in release YAML.
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#290 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#289 Update comment in main.go.
  cmd/controller/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#291 Fix typo and phrasing.
  cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/XS

#292 enable code coverage
  .codecov.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#293 Add NodePort Service profiles.
  third_party/istio-latest/istio-ci-mesh-node-port.yaml
  third_party/istio-latest/istio-ci-no-mesh-node-port.yaml
  third_party/istio-stable/istio-ci-mesh-node-port.yaml
  third_party/istio-stable/istio-ci-no-mesh-node-port.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#295 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#298 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#302 Move Webhooks to v1 API.
  config/500-mutating-webhook.yaml
  config/500-validating-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#303 Rename and tweak Kind profiles.
  third_party/istio-latest/istio-kind-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-stable/istio-kind-mesh.yaml
  third_party/istio-stable/istio-kind-no-mesh.yaml
Labels: approved, cla: yes, lgtm, size/L

#304 [master] Update GitHub Actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#305 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#306 Tune CodeCov down a little bit.
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/S

#307 [Release-0.18] Pin deps to release-0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#310 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#309 Remove deprecated fields.
  third_party/istio-latest/extra/global-mtls.yaml
  third_party/istio-latest/install-istio.sh
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-kind-mesh.yaml
Labels: approved, cla: yes, lgtm, size/S

#314 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#315 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#316 Fix net istio for proper test formatting
  pkg/reconciler/accessor/core/secret_test.go
  pkg/reconciler/accessor/istio/virtualservice_test.go
  pkg/reconciler/accessor/networking/certificate_test.go
  pkg/reconciler/ingress/config/istio_test.go
  pkg/reconciler/ingress/config/store_test.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister_test.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/secret_test.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, lgtm, size/L

#317 Fix the format here
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/XS

#318 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#319 Enable extended linting and fix the respective issues
  .golangci.yaml
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/virtual_service.go
  test/e2e/clients.go
Labels: approved, cla: yes, lgtm, size/M

#320 Specify port for rewrite host destination
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, lgtm, size/S

#321 Make the Codecov settings uniform
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/XS
