Repository knative-extensions/net-istio, pull requests merged in 2020-08, with the labels that each got.

#205 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/go-logr/logr/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/klog/v2/LICENSE
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/any_str.go
  vendor/github.com/json-iterator/go/config.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_optional.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/json-iterator/go/reflect_struct_encoder.go
  vendor/github.com/json-iterator/go/stream.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/config.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/increase_level.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/utils/pointer/README.md
  vendor/k8s.io/utils/trace/README.md
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/test/prober.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#207 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#208 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#170 Generate per-Ingress Gateway instead of reconciling the global Ingress Gateway when auto TLS is enabled
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
Labels: approved, cla: yes, lgtm, size/L

#206 Replace the DEPRECATED Track method
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/secret.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#214 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#215 Pin some knative.dev deps to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#216 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/hosts.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#217 Stable = 1.4.6, Latest = 1.5.7
  third_party/istio-1.4.6/install-istio.sh
  third_party/istio-1.4.6/istio-ci-mesh.yaml
  third_party/istio-1.4.6/istio-ci-no-mesh.yaml
  third_party/istio-1.4.6/istio-crds.yaml
  third_party/istio-1.4.6/istio-knative-extras.yaml
  third_party/istio-1.4.6/istio-minimal.yaml
  third_party/istio-1.6.5/README.md
  third_party/istio-1.6.5/install-istio.sh
  third_party/istio-1.6.5/istio-ci-mesh.yaml
  third_party/istio-1.6.5/istio-ci-no-mesh.yaml
  third_party/istio-1.6.5/istio-minimal.yaml
  third_party/istio-latest
  third_party/istio-stable
Labels: approved, cla: yes, lgtm, size/XXL

#219 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#221 Run tests with NodeLocalDNS enabled
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#222 Run 5 parallel invocations for KIngress conformance tests.
  test/conformance/ingress_test.go
Labels: approved, cla: yes, lgtm, size/S

#223 Turn it up to 11
  test/conformance/ingress_test.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#225 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#227 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/rewrite.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#229 Remove `-parallel=12` to match Serving e2e & increase test runs.
  test/conformance/ingress_test.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#230 Remove knative.dev/serving dep
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#233 Track master again now that release-0.17 is snapped.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/pkg/probe_handler.go
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/hosts.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/rewrite.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/kmp/diff.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#178 Exclude Webhooks from mTLS STRICT
  config/400-webhook-peer-authentication.yaml
Labels: approved, cla: yes, lgtm, size/S

#246 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#247 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#237 Add new local Gateway sharing same deployment as ingress Gateway.
  config/203-local-gateway.yaml
  pkg/reconciler/ingress/config/istio.go
Labels: approved, cla: yes, lgtm, size/M

#248 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#250 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#251 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/system/testing/names.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#213 Move istio specific tests from test/e2e/istio in serving repo
  test/config/chaosduck.yaml
  test/e2e-tests.sh
  test/e2e/clients.go
  test/e2e/e2e.go
  test/e2e/probing_test.go
  third_party/VENDOR-LICENSE/github.com/openzipkin/zipkin-go/model/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/networking/LICENSE
Labels: approved, cla: yes, lgtm, size/XL

#257 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
