Repository knative-extensions/net-istio, pull requests merged in 2020-11, with the labels that each got.

#396 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#394 Run net-istio tests on KinD with non-default cluster suffix
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/L

#398 Add missing labels to PeerAuthentication.
  config/400-webhook-peer-authentication.yaml
Labels: approved, cla: yes, lgtm, size/XS

#399 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#400 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#401 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#402 Include commit ID in component YAML instead of release YAML.
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#403 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/S

#404 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#407 Replace sample-controller with net-istio in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#408 [Automated] Format markdown
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#405 Use mesh mode when sidecar injection is enabled
  third_party/istio-latest/install-istio.sh
  third_party/istio-stable/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#409 Update Istio latest to 1.7.4.
  third_party/istio-latest/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#410 Drop manually updating observed generation
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/XS

#412 Rename file to comply with divisive language
  config/placeholder.go
  third_party/istio-stable/placeholder.go
Labels: approved, cla: yes, lgtm, size/XS

#415 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#413 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/main.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/proc.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#411 Remove `cluster-local-gateway`.
  config/203-local-gateway.yaml
  config/config.yaml
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-kind-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-minimal.yaml
  third_party/istio-stable/istio-ci-mesh.yaml
  third_party/istio-stable/istio-ci-no-mesh.yaml
  third_party/istio-stable/istio-kind-mesh.yaml
  third_party/istio-stable/istio-kind-no-mesh.yaml
  third_party/istio-stable/istio-minimal.yaml
Labels: approved, cla: yes, lgtm, size/L

#416 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#418 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#420 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#423 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#424 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#425 Support OSes other than linux in install-istio.sh
  third_party/istio-latest/install-istio.sh
  third_party/istio-stable/install-istio.sh
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#428 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#429 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/networking/pkg/testing/status/fake.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#430 Drop unused helloworld image
  hack/tools.go
  vendor/knative.dev/networking/test/test_images/helloworld/helloworld.go
  vendor/knative.dev/networking/test/test_images/helloworld/helloworld.yaml
  vendor/knative.dev/networking/test/test_images/helloworld/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#432 Remove the trailing space
  config/400-webhook-peer-authentication.yaml
Labels: approved, cla: yes, lgtm, size/XS
