Repository knative-extensions/net-istio, pull requests merged in 2020-12, with the labels that each got.

#431 Build for all platforms
  hack/release.sh
  test/e2e-common.sh
  test/upload-test-images.sh
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#434 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#436 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#427 Remove extra brackets in table test
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#437 Update Istio stable to 1.7.4 and latest to 1.7.5.
  third_party/istio-stable/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#441 Update deps
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/networking/pkg/prober/doc.go
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#443 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#442 Fix the lint issue.
  test/e2e/probing_test.go
Labels: approved, cla: yes, lgtm, size/XS

#444 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#445 Update istio-latest to 1.8.1
  third_party/istio-latest/install-istio.sh
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-kind-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-minimal.yaml
Labels: approved, cla: yes, lgtm, size/S

#447 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#448 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#449 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#450 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#452 Remove flaky test image
  hack/tools.go
  vendor/knative.dev/networking/test/test_images/flaky/main.go
  vendor/knative.dev/networking/test/test_images/flaky/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, kind/cleanup, lgtm

#453 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#438 Integrate the gopath hacks
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/S

#456 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#458 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#460 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#459 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#462 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#464 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#465 Use ko 0.6.0 release
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#466 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#467 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#355 Get status of VirtualService if available and use that to determine ingress readiness
  config/config.yaml
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#468 Run istio status tests in istio-latest
  third_party/istio-latest/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#469 Fix tiny logging/comment/naming bugs in virtualservice status test
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, size/S

#473 Update Istio stable to 1.7.6.
  third_party/istio-stable/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#471 Move istio config patches into a separate file
  third_party/istio-latest/extra/configure-istio.sh
  third_party/istio-latest/install-istio.sh
  third_party/istio-stable/extra/configure-istio.sh
  third_party/istio-stable/install-istio.sh
Labels: approved, cla: yes, lgtm, size/M

#474 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
