Repository knative-extensions/net-istio, pull requests merged in 2020-03, with the labels that each got.

#9 Use the published contributing links.
  CONTRIBUTING.md
  DEVELOPMENT.md
  Gopkg.lock
  pkg/doc.go
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/gobuffalo/envy/LICENSE
  vendor/github.com/gobuffalo/envy/LICENSE.txt
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/joho/godotenv/LICENCE
  vendor/github.com/joho/godotenv/godotenv.go
  vendor/github.com/markbates/inflect/LICENCE
  vendor/github.com/markbates/inflect/helpers.go
  vendor/github.com/markbates/inflect/inflect.go
  vendor/github.com/markbates/inflect/name.go
  vendor/github.com/markbates/inflect/version.go
  vendor/github.com/rogpeppe/go-internal/LICENSE
  vendor/github.com/rogpeppe/go-internal/modfile/gopkgin.go
  vendor/github.com/rogpeppe/go-internal/modfile/print.go
  vendor/github.com/rogpeppe/go-internal/modfile/read.go
  vendor/github.com/rogpeppe/go-internal/modfile/rule.go
  vendor/github.com/rogpeppe/go-internal/module/module.go
  vendor/github.com/rogpeppe/go-internal/semver/semver.go
  vendor/golang.org/x/net/http2/h2c/h2c.go
  vendor/gomodules.xyz/jsonpatch/LICENSE
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/k8s.io/apimachinery/pkg/api/validation/generic.go
  vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/client-go/discovery/fake/discovery.go
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
Labels: approved, lgtm, size/XXL

#7 Add an `--upgrade` flag to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, lgtm, size/S

#11 Auto-update dependencies
  Gopkg.lock
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/testdata/README.md
  vendor/knative.dev/pkg/metrics/testdata/client-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/client-key.pem
  vendor/knative.dev/pkg/metrics/testdata/server-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/server-key.pem
Labels: approved, lgtm, size/XXL

#10 Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#15 Add serving to the list of dependencies to float in net-istio
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#16 Add `hack/release.sh` to unblock releasing `net-istio`.
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/M

#19 Add update-licences call based on knative/serving/pull/7152
  cmd/networking/doc.go
  hack/update-deps.sh
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#17 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/resources/virtual_service.go
  vendor/knative.dev/serving/pkg/resources/doc.go
  vendor/knative.dev/serving/pkg/resources/endpoints.go
  vendor/knative.dev/serving/pkg/resources/meta.go
  vendor/knative.dev/serving/pkg/resources/pods.go
  vendor/knative.dev/serving/pkg/resources/scale.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#4 Add istio defaulting webhook
  Gopkg.lock
  cmd/webhook/main.go
  config/500-webhook.yaml
  config/webhook-service.yaml
  pkg/defaults/deployment_defaults.go
  third_party/VENDOR-LICENSE
  vendor/github.com/gobuffalo/envy/LICENSE
  vendor/github.com/gobuffalo/envy/LICENSE.txt
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/joho/godotenv/LICENCE
  vendor/github.com/joho/godotenv/godotenv.go
  vendor/github.com/markbates/inflect/LICENCE
  vendor/github.com/markbates/inflect/helpers.go
  vendor/github.com/markbates/inflect/inflect.go
  vendor/github.com/markbates/inflect/name.go
  vendor/github.com/markbates/inflect/version.go
  vendor/github.com/rogpeppe/go-internal/LICENSE
  vendor/github.com/rogpeppe/go-internal/modfile/gopkgin.go
  vendor/github.com/rogpeppe/go-internal/modfile/print.go
  vendor/github.com/rogpeppe/go-internal/modfile/read.go
  vendor/github.com/rogpeppe/go-internal/modfile/rule.go
  vendor/github.com/rogpeppe/go-internal/module/module.go
  vendor/github.com/rogpeppe/go-internal/semver/semver.go
Labels: approved, cla: yes, lgtm, size/XXL

#20 Backfill tests for deployment defaults
  pkg/defaults/deployment_defaults.go
  pkg/defaults/deployment_defaults_test.go
Labels: approved, cla: yes, lgtm, size/L

#21 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/serving/pkg/network/status/status.go
Labels: approved, cla: yes, lgtm, size/XS

#22 Remove unnecessary nesting under ../networking/istio or istio-ingress/...
  Gopkg.lock
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/LICENSE
  cmd/controller/kodata/VENDOR-LICENSE
  cmd/controller/kodata/refs
  cmd/controller/main.go
  cmd/networking/doc.go
  cmd/networking/istio/kodata/HEAD
  cmd/networking/istio/kodata/LICENSE
  cmd/networking/istio/kodata/VENDOR-LICENSE
  cmd/networking/istio/kodata/refs
  cmd/networking/istio/main.go
  config/200-clusterrole.yaml
  config/202-gateway.yaml
  config/203-local-gateway.yaml
  config/config.yaml
  config/controller.yaml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/serving/pkg/reconciler/accessor/core/secret.go
  vendor/knative.dev/serving/pkg/reconciler/accessor/errors.go
  vendor/knative.dev/serving/pkg/reconciler/accessor/istio/virtualservice.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/config/doc.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/config/istio.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/config/store.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/controller.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/doc.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/ingress.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/lister.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/resources/doc.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/resources/gateway.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/resources/names/doc.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/resources/names/names.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/resources/secret.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/resources/virtual_service.go
Labels: approved, cla: yes, lgtm, size/XXL

#24 Make release script track config directory move
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#25 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/serving/config/200-clusterrole-ns-wildcard-certs.yaml
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#26 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/serving/config/200-clusterrole-istio.yaml
  vendor/knative.dev/serving/config/202-gateway.yaml
  vendor/knative.dev/serving/config/203-local-gateway.yaml
  vendor/knative.dev/serving/config/config-istio.yaml
  vendor/knative.dev/serving/config/net-istio.yaml
  vendor/knative.dev/serving/config/networking-istio.yaml
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/config/testdata/config-istio.yaml
Labels: approved, cla: yes, lgtm, size/M

#29 Use ko's strict mode for better errors messages
  config/controller.yaml
  config/webhook-service.yaml
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#28 Validate configmap config-istio in Istio ingress webhook.
  Gopkg.lock
  cmd/webhook/main.go
  config/500-webhook-configmap.yaml
  vendor/knative.dev/pkg/metrics/exporter.go
Labels: approved, cla: yes, lgtm, size/M

#31 Pull conformance/ingress tests into vendor/
  Gopkg.lock
  Gopkg.toml
  hack/update-deps.sh
  test/pkg.go
  vendor/knative.dev/serving/cmd/networking/istio/kodata/HEAD
  vendor/knative.dev/serving/cmd/networking/istio/kodata/LICENSE
  vendor/knative.dev/serving/cmd/networking/istio/kodata/VENDOR-LICENSE
  vendor/knative.dev/serving/cmd/networking/istio/kodata/refs
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/README.md
  vendor/knative.dev/serving/pkg/reconciler/ingress/config/testdata/config-network.yaml
  vendor/knative.dev/serving/test/README.md
  vendor/knative.dev/serving/test/adding_tests.md
  vendor/knative.dev/serving/test/apicoverage.sh
  vendor/knative.dev/serving/test/conformance/ingress/basic_test.go
  vendor/knative.dev/serving/test/conformance/ingress/grpc_test.go
  vendor/knative.dev/serving/test/conformance/ingress/headers_test.go
  vendor/knative.dev/serving/test/conformance/ingress/hosts_test.go
  vendor/knative.dev/serving/test/conformance/ingress/path_test.go
  vendor/knative.dev/serving/test/conformance/ingress/percentage_test.go
  vendor/knative.dev/serving/test/conformance/ingress/retry_test.go
  vendor/knative.dev/serving/test/conformance/ingress/timeout_test.go
  vendor/knative.dev/serving/test/conformance/ingress/tls_test.go
  vendor/knative.dev/serving/test/conformance/ingress/update_test.go
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/knative.dev/serving/test/conformance/ingress/visibility_test.go
  vendor/knative.dev/serving/test/conformance/ingress/websocket_test.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-basic-entrypoint.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/e2e/README.md
  vendor/knative.dev/serving/test/presubmit-tests.sh
  vendor/knative.dev/serving/test/types/runtime.go
  vendor/knative.dev/serving/test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, size/XXL

#32 Download test_images and conformance tests.
  Gopkg.lock
  Gopkg.toml
  hack/update-deps.sh
  test/upload-test-images.sh
  vendor/knative.dev/serving/test/test_images/grpc-ping/main.go
  vendor/knative.dev/serving/test/test_images/grpc-ping/proto/ping.pb.go
  vendor/knative.dev/serving/test/test_images/grpc-ping/proto/ping.proto
  vendor/knative.dev/serving/test/test_images/grpc-ping/service.yaml
  vendor/knative.dev/serving/test/test_images/runtime/handlers/args.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/cgroup.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/env.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/file.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/file_access_attempt.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/mount.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/proc.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/request.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/runtime.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/user.go
  vendor/knative.dev/serving/test/test_images/runtime/main.go
  vendor/knative.dev/serving/test/test_images/runtime/service.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#35 Run knative.dev/serving/test/conformance/ingress tests for presubmit
  Gopkg.lock
  Gopkg.toml
  test/config/100-serving-namespace.yaml
  test/config/100-test-namespace.yaml
  test/config/200-clusterrole-namespaced.yaml
  test/config/200-service-account.yaml
  test/config/201-clusterrole-core.yaml
  test/config/300-ingress.yaml
  test/config/config-autoscaler.yaml
  test/config/config-defaults.yaml
  test/config/config-logging.yaml
  test/config/config-network.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  test/upload-test-images.sh
  third_party/istio-1.4.4/README.md
  third_party/istio-1.4.4/download-istio.sh
  third_party/istio-1.4.4/drain-seconds.yaml.patch
  third_party/istio-1.4.4/istio-ci-mesh.yaml
  third_party/istio-1.4.4/istio-ci-no-mesh.yaml
  third_party/istio-1.4.4/istio-crds.yaml
  third_party/istio-1.4.4/istio-knative-extras.yaml
  third_party/istio-1.4.4/istio-minimal.yaml
  third_party/istio-1.4.4/namespace.yaml.patch
  third_party/istio-1.4.4/values-extras.yaml
  third_party/istio-1.4.4/values-lean.yaml
  third_party/istio-1.4.4/values-local.yaml
  third_party/istio-1.4.4/values.yaml
  third_party/istio-latest
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/serving/test/conformance/ingress/visibility_test.go
  vendor/knative.dev/serving/test/prober.go
  vendor/knative.dev/serving/test/test_images/flaky/README.md
  vendor/knative.dev/serving/test/test_images/flaky/main.go
  vendor/knative.dev/serving/test/test_images/flaky/service.yaml
  vendor/knative.dev/serving/test/test_images/grpc-ping/service.yaml
  vendor/knative.dev/serving/test/test_images/httpproxy/README.md
  vendor/knative.dev/serving/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/serving/test/test_images/httpproxy/service.yaml
  vendor/knative.dev/serving/test/test_images/runtime/service.yaml
  vendor/knative.dev/serving/test/test_images/timeout/README.md
  vendor/knative.dev/serving/test/test_images/timeout/service.yaml
  vendor/knative.dev/serving/test/test_images/timeout/timeout.go
  vendor/knative.dev/serving/test/test_images/wsserver/README.md
  vendor/knative.dev/serving/test/test_images/wsserver/echo.go
  vendor/knative.dev/serving/test/test_images/wsserver/service.yaml
  vendor/knative.dev/serving/test/v1alpha1/configuration.go
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XXL

#38 Trim down test resources.
  test/config/200-clusterrole-namespaced.yaml
  test/config/201-clusterrole-core.yaml
  test/config/config-autoscaler.yaml
  test/config/config-defaults.yaml
  test/config/config-logging.yaml
  test/config/config-network.yaml
Labels: approved, cla: yes, lgtm, size/L

#41 Autogen DeepCopy instead of manually creating
  hack/update-codegen.sh
  pkg/defaults/deployment_defaults.go
  pkg/defaults/doc.go
  pkg/defaults/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/M

#42 Add kodata for webhook
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/LICENSE
  cmd/webhook/kodata/VENDOR-LICENSE
  cmd/webhook/kodata/refs
Labels: approved, cla: yes, lgtm, size/XS

#43 Fix VirtualService generation: gateways field
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#45 Update owners.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#46 Fix name for istio canonical service names.
  pkg/defaults/deployment_defaults.go
  pkg/defaults/deployment_defaults_test.go
Labels: approved, cla: yes, lgtm, size/S

#49 Remove the cross namespace OwnerReference
  pkg/reconciler/accessor/core/secret.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
Labels: approved, cla: yes, lgtm, size/L

#54 Remove obsoleted WebsocketUpgrade from VirtualService
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, lgtm, size/XS

#55 Add a flag for Istio version, also run tests using 'stable' version.
  test/e2e-common.sh
  third_party/istio-1.4.6/README.md
  third_party/istio-1.4.6/download-istio.sh
  third_party/istio-1.4.6/drain-seconds.yaml.patch
  third_party/istio-1.4.6/istio-ci-mesh.yaml
  third_party/istio-1.4.6/istio-ci-no-mesh.yaml
  third_party/istio-1.4.6/istio-crds.yaml
  third_party/istio-1.4.6/istio-knative-extras.yaml
  third_party/istio-1.4.6/istio-minimal.yaml
  third_party/istio-1.4.6/namespace.yaml.patch
  third_party/istio-1.4.6/values-extras.yaml
  third_party/istio-1.4.6/values-lean.yaml
  third_party/istio-1.4.6/values-local.yaml
  third_party/istio-1.4.6/values.yaml
  third_party/istio-stable
Labels: approved, cla: yes, lgtm, size/XXL

#56 Fix presubmit tests argument passing.
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#57 [master] golang format tools
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#58 Fix log format issue
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/XS
