Repository knative-extensions/net-istio, pull requests merged in 2021-02, with the labels that each got.

#501 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#502 Update Istio stable to 1.7.7.
  third_party/istio-stable/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#504 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#499 peer auth: Only set permissive mTLS on the webhook port.
  config/400-webhook-peer-authentication.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, ok-to-test, size/S

#506 Clean up cluster-local-gateway in test code
  pkg/reconciler/ingress/config/testdata/config-istio.yaml
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/S

#505 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#507 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#508 Re-introduce behaviour of explicitly setting retries to 0
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#511 Ignore status if ObservedGeneration == 0
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, kind/bug, lgtm, size/L

#497 Add ability to install istio from HEAD
  third_party/download-istio.sh
  third_party/istio-head/README.md
  third_party/istio-head/extra/configure-istio.sh
  third_party/istio-head/extra/global-mtls.yaml
  third_party/istio-head/install-istio.sh
  third_party/istio-head/istio-ci-mesh.yaml
  third_party/istio-head/istio-ci-no-mesh.yaml
  third_party/istio-head/istio-kind-mesh.yaml
  third_party/istio-head/istio-kind-no-mesh.yaml
  third_party/istio-head/istio-minimal.yaml
Labels: approved, cla: yes, lgtm, size/L

#512 Properly implement Splits support in RewriteHost
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#513 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#516 Bump Golang version to 1.15
  go.mod
Labels: approved, cla: yes, lgtm, size/XS

#515 Move 1.8.2 to stable and 1.9.0 to latest
  third_party/istio-latest/install-istio.sh
  third_party/istio-stable/extra/istio-namespace.yaml
  third_party/istio-stable/install-istio.sh
  third_party/istio-stable/istio-ci-mesh.yaml
  third_party/istio-stable/istio-ci-no-mesh.yaml
  third_party/istio-stable/istio-kind-mesh.yaml
  third_party/istio-stable/istio-kind-no-mesh.yaml
  third_party/istio-stable/istio-minimal.yaml
  third_party/istio-stable/placeholder.go
Labels: approved, cla: yes, lgtm, size/M

#517 Temporarily disable mTLS STRICT in mesh mode.
  third_party/istio-stable/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#518 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#519 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#520 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#521 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#522 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#523 Add namespace to stable's extra folder to fix nightly builds
  third_party/istio-stable/extra/istio-namespace.yaml
Labels: approved, cla: yes, lgtm, size/S

#524 Add placeholder.go back to fix docs
  third_party/istio-stable/placeholder.go
Labels: approved, cla: yes, lgtm, size/S

#525 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/S

#526 Bump k8s version in kind e2e
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/S
