Repository knative-extensions/net-istio, pull requests merged in 2021-11, with the labels that each got.

#798 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#799 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#800 Document maturity levels in sandbox
  README.md
Labels: size/XS, approved, lgtm, cla: yes

#802 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#803 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, approved, lgtm, cla: yes

#791 Revert "Use GKE 1.20 (#781)"
  test/e2e-tests.sh
Labels: size/XS, approved, lgtm, cla: yes

#805 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#807 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#806 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, cla: yes, size/M

#808 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#804 Add k8s recommended labels
  config/200-clusterrole.yaml
  config/202-gateway.yaml
  config/203-local-gateway.yaml
  config/400-config-istio.yaml
  config/400-webhook-peer-authentication.yaml
  config/500-controller.yaml
  config/500-webhook-deployment.yaml
  config/500-webhook-secret.yaml
  config/500-webhook-service.yaml
  config/600-mutating-webhook.yaml
  config/600-validating-webhook.yaml
  hack/release.sh
  pkg/reconciler/ingress/config/testdata/config-istio.yaml
  pkg/reconciler/ingress/config/testdata/config-network.yaml
  test/config/200-service-account.yaml
  third_party/istio-head/extra/config-istio-mesh.yaml
  third_party/istio-head/extra/config-istio.yaml
  third_party/istio-head/istio-ci-mesh/config-istio.yaml
  third_party/istio-head/istio-ci-no-mesh/config-istio.yaml
  third_party/istio-head/istio-kind-mesh/config-istio.yaml
  third_party/istio-head/istio-kind-no-mesh/config-istio.yaml
  third_party/istio-latest/extra/config-istio-mesh.yaml
  third_party/istio-latest/extra/config-istio.yaml
  third_party/istio-latest/istio-ci-mesh/config-istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/config-istio.yaml
  third_party/istio-latest/istio-kind-mesh/config-istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/config-istio.yaml
Labels: approved, lgtm, cla: yes, size/L, kind/enhancement

#809 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#811 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, cla: yes

#810 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#812 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#813 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#816 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#818 Disable enable-virtualservice-status on istio-head test
  third_party/istio-head/extra/config-istio-mesh.yaml
  third_party/istio-head/extra/config-istio.yaml
  third_party/istio-head/extra/configure-istio.sh
  third_party/istio-head/istio-ci-mesh/config-istio.yaml
  third_party/istio-head/istio-ci-no-mesh/config-istio.yaml
  third_party/istio-head/istio-kind-mesh/config-istio.yaml
  third_party/istio-head/istio-kind-no-mesh/config-istio.yaml
  third_party/istio-latest/extra/config-istio-mesh.yaml
  third_party/istio-latest/extra/config-istio.yaml
  third_party/istio-latest/extra/configure-istio.sh
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/config-istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/config-istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-mesh/config-istio.yaml
  third_party/istio-latest/istio-kind-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/config-istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  third_party/istio-stable/generate-manifests.sh
  third_party/istio-stable/istio-ci-mesh/istio.yaml
  third_party/istio-stable/istio-ci-no-mesh/istio.yaml
  third_party/istio-stable/istio-kind-mesh/istio.yaml
  third_party/istio-stable/istio-kind-no-mesh/istio.yaml
Labels: approved, size/XXL, lgtm, cla: yes

#821 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, approved, lgtm, cla: yes

#822 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M
