Repository knative-extensions/net-istio, pull requests merged in 2021-09, with the labels that each got.

#745 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#746 [release-0.25] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#747 drop scheduled actions these fill up the job queue causing delays
  .github/workflows/kind-e2e.yaml
Labels: size/XS, approved, lgtm, cla: yes

#748 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#750 [release-0.24] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/library.sh
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#751 [release-0.22] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#752 [release-0.23] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/library.sh
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#754 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#756 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#757 [release-0.22] drop ko strict
  hack/release.sh
Labels: size/XS, approved, lgtm, cla: yes

#758 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#759 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#760 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/state.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#762 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#763 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/test/conformance/ingress/httpoption.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#765 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#764 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, cla: yes

#766 Drop K8s 1.19 as it's no longer supported
  .github/workflows/kind-e2e.yaml
Labels: size/XS, approved, lgtm, cla: yes

#768 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/S, cla: yes

#767 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#771 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#770 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, approved, lgtm, cla: yes

#772 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#773 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/S, cla: yes

#774 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#776 [main] Update community files
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, cla: yes, size/M

#761 Bump istio client deps version to v1.10.3
  go.mod
  go.sum
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.go
  vendor/istio.io/api/networking/v1alpha3/virtual_service.pb.html
  vendor/istio.io/api/networking/v1alpha3/virtual_service.proto
  vendor/istio.io/api/networking/v1beta1/virtual_service.pb.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.proto
  vendor/istio.io/client-go/pkg/apis/networking/v1alpha3/types.gen.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L, kind/cleanup
