Repository knative-extensions/net-istio, pull requests merged in 2021-12, with the labels that each got.

#820 Remove istio-stable from test
  .github/workflows/kind-e2e.yaml
  hack/release.sh
  hack/update-codegen.sh
  test/e2e-common.sh
  third_party/istio-stable/README.md
  third_party/istio-stable/extra/istio-mesh.yaml
  third_party/istio-stable/generate-manifests.sh
  third_party/istio-stable/install-istio.sh
  third_party/istio-stable/istio-ci-mesh.yaml
  third_party/istio-stable/istio-ci-mesh/istio.yaml
  third_party/istio-stable/istio-ci-no-mesh.yaml
  third_party/istio-stable/istio-ci-no-mesh/istio.yaml
  third_party/istio-stable/istio-kind-mesh.yaml
  third_party/istio-stable/istio-kind-mesh/istio.yaml
  third_party/istio-stable/istio-kind-no-mesh.yaml
  third_party/istio-stable/istio-kind-no-mesh/istio.yaml
  third_party/istio-stable/placeholder.go
Labels: approved, size/XXL, lgtm, cla: yes

#823 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, cla: yes

#824 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, cla: yes

#826 Remove istio-kind-mesh.yaml
  third_party/istio-head/generate-manifests.sh
  third_party/istio-head/istio-ci-mesh.yaml
  third_party/istio-head/istio-kind-mesh.yaml
  third_party/istio-head/istio-kind-mesh/istio.yaml
  third_party/istio-latest/istio-kind-mesh.yaml
  third_party/istio-latest/istio-kind-mesh/istio.yaml
Labels: approved, size/XXL, lgtm, cla: yes

#828 Bump Istio head
  third_party/istio-head/istio-ci-mesh.yaml
  third_party/istio-head/istio-ci-mesh/istio.yaml
  third_party/istio-head/istio-ci-no-mesh/istio.yaml
  third_party/istio-head/istio-kind-no-mesh/istio.yaml
Labels: approved, size/XXL, lgtm

#829 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/rs/dnscache/.travis.yml
  vendor/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/README.md
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/github.com/rs/dnscache/go.mod
  vendor/github.com/rs/dnscache/go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#831 Drop explicit indirect dependencies
  go.mod
  go.sum
  vendor/github.com/go-openapi/jsonpointer/.travis.yml
  vendor/github.com/go-openapi/jsonpointer/pointer.go
  vendor/github.com/go-openapi/jsonreference/.golangci.yml
  vendor/github.com/go-openapi/jsonreference/.travis.yml
  vendor/github.com/go-openapi/jsonreference/README.md
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/github.com/go-openapi/spec/contact_info.go
  vendor/github.com/go-openapi/spec/license.go
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/go-openapi/swag/.travis.yml
  vendor/github.com/go-openapi/swag/README.md
  vendor/github.com/go-openapi/swag/convert.go
  vendor/github.com/go-openapi/swag/convert_types.go
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/loading.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/josharian/intern/README.md
  vendor/github.com/josharian/intern/go.mod
  vendor/github.com/josharian/intern/intern.go
  vendor/github.com/josharian/intern/license.md
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#832 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/rs/dnscache/.travis.yml
  vendor/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/README.md
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/github.com/rs/dnscache/go.mod
  vendor/github.com/rs/dnscache/go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#834 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#835 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm
