Repository knative-extensions/net-istio, pull requests merged in 2021-08, with the labels that each got.

#713 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#714 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#717 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#716 Bump Golang version to 1.16
  .github/workflows/kind-e2e.yaml
  go.mod
Labels: size/XS, approved, lgtm, cla: yes

#720 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#722 Bump Istio stable and latest to 1.10.3 and 1.11.0
  hack/update-codegen.sh
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  third_party/istio-stable/generate-manifests.sh
  third_party/istio-stable/istio-ci-mesh/istio.yaml
  third_party/istio-stable/istio-ci-no-mesh/istio.yaml
  third_party/istio-stable/istio-kind-mesh/istio.yaml
  third_party/istio-stable/istio-kind-no-mesh/istio.yaml
Labels: approved, size/XXL, lgtm, cla: yes

#724 [main] Format Go code
  hack/tools.go
  test/conformance/ingress_test.go
  test/e2e/probing_test.go
Labels: size/XS, approved, lgtm, cla: yes

#728 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, cla: yes

#727 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, approved, lgtm, cla: yes

#726 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/istio/injection/client/client.go
  pkg/client/istio/injection/informers/networking/v1alpha3/destinationrule/destinationrule.go
  pkg/client/istio/injection/informers/networking/v1alpha3/destinationrule/filtered/destinationrule.go
  pkg/client/istio/injection/informers/networking/v1alpha3/envoyfilter/envoyfilter.go
  pkg/client/istio/injection/informers/networking/v1alpha3/envoyfilter/filtered/envoyfilter.go
  pkg/client/istio/injection/informers/networking/v1alpha3/gateway/filtered/gateway.go
  pkg/client/istio/injection/informers/networking/v1alpha3/gateway/gateway.go
  pkg/client/istio/injection/informers/networking/v1alpha3/serviceentry/filtered/serviceentry.go
  pkg/client/istio/injection/informers/networking/v1alpha3/serviceentry/serviceentry.go
  pkg/client/istio/injection/informers/networking/v1alpha3/sidecar/filtered/sidecar.go
  pkg/client/istio/injection/informers/networking/v1alpha3/sidecar/sidecar.go
  pkg/client/istio/injection/informers/networking/v1alpha3/virtualservice/filtered/virtualservice.go
  pkg/client/istio/injection/informers/networking/v1alpha3/virtualservice/virtualservice.go
  pkg/client/istio/injection/informers/networking/v1alpha3/workloadentry/filtered/workloadentry.go
  pkg/client/istio/injection/informers/networking/v1alpha3/workloadentry/workloadentry.go
  pkg/client/istio/injection/informers/networking/v1alpha3/workloadgroup/filtered/workloadgroup.go
  pkg/client/istio/injection/informers/networking/v1alpha3/workloadgroup/workloadgroup.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/client/injection/client/client.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/certificate/certificate.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/ingress/ingress.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/serverlessservice/serverlessservice.go
  vendor/knative.dev/networking/test/conformance/ingress/rewrite.go
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/dynamicclient/dynamicclient.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes

#729 Fix deprecation lint error
  pkg/reconciler/ingress/ingress_test.go
Labels: size/XS, approved, lgtm, cla: yes

#730 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#732 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#734 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L
