Repository knative-extensions/net-istio, pull requests merged in 2021-01, with the labels that each got.

#475 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#476 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#478 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#472 Add test for virtualservice status config
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/config/istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#481 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#484 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#482 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#485 Clean up some formatting and tidy loop
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#486 Update istio-latest to 1.8.2
  third_party/istio-latest/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#487 Various cleanups
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/gateway.go
Labels: approved, cla: yes, lgtm, size/M

#488 [] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/istio/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/istio/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/istio/injection/informers/networking/v1alpha3/destinationrule/filtered/destinationrule.go
  pkg/client/istio/injection/informers/networking/v1alpha3/destinationrule/filtered/fake/fake.go
  pkg/client/istio/injection/informers/networking/v1alpha3/envoyfilter/filtered/envoyfilter.go
  pkg/client/istio/injection/informers/networking/v1alpha3/envoyfilter/filtered/fake/fake.go
  pkg/client/istio/injection/informers/networking/v1alpha3/gateway/filtered/fake/fake.go
  pkg/client/istio/injection/informers/networking/v1alpha3/gateway/filtered/gateway.go
  pkg/client/istio/injection/informers/networking/v1alpha3/serviceentry/filtered/fake/fake.go
  pkg/client/istio/injection/informers/networking/v1alpha3/serviceentry/filtered/serviceentry.go
  pkg/client/istio/injection/informers/networking/v1alpha3/sidecar/filtered/fake/fake.go
  pkg/client/istio/injection/informers/networking/v1alpha3/sidecar/filtered/sidecar.go
  pkg/client/istio/injection/informers/networking/v1alpha3/virtualservice/filtered/fake/fake.go
  pkg/client/istio/injection/informers/networking/v1alpha3/virtualservice/filtered/virtualservice.go
  pkg/client/istio/injection/informers/networking/v1alpha3/workloadentry/filtered/fake/fake.go
  pkg/client/istio/injection/informers/networking/v1alpha3/workloadentry/filtered/workloadentry.go
  pkg/client/istio/injection/informers/networking/v1alpha3/workloadgroup/filtered/fake/fake.go
  pkg/client/istio/injection/informers/networking/v1alpha3/workloadgroup/filtered/workloadgroup.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#489 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#490 Add placeholder.go under third_party
  third_party/placeholder.go
Labels: approved, cla: yes, lgtm, size/S

#493 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/serverlessservice.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#491 Add errorlint and fix all existing issues
  .golangci.yaml
  pkg/reconciler/accessor/errors.go
  pkg/reconciler/ingress/resources/util.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/S

#494 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#495 Add permissive PeerAuthentication for domainmapping-webhook
  config/400-webhook-peer-authentication.yaml
Labels: approved, cla: yes, lgtm, size/S

#498 Fix mesh tests
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S
