Repository knative-extensions/net-istio, pull requests merged in 2021-05, with the labels that each got.

#618 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/S

#619 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#600 Drop istio-minimal.yaml
  DEVELOPMENT.md
  third_party/istio-head/README.md
  third_party/istio-head/istio-minimal.yaml
  third_party/istio-head/istio-minimal/config-istio.yaml
  third_party/istio-head/istio-minimal/istio.yaml
  third_party/istio-latest/README.md
  third_party/istio-latest/istio-minimal.yaml
  third_party/istio-latest/istio-minimal/config-istio.yaml
  third_party/istio-latest/istio-minimal/istio.yaml
  third_party/istio-stable/README.md
  third_party/istio-stable/istio-minimal.yaml
  third_party/istio-stable/istio-minimal/istio.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XXL

#621 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#622 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#623 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#626 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#627 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#628 Add NotOwnedFailure test
  pkg/reconciler/accessor/istio/destinationrule_test.go
  pkg/reconciler/accessor/istio/virtualservice_test.go
  pkg/reconciler/accessor/networking/certificate_test.go
Labels: approved, cla: yes, lgtm, size/L

#629 Replace golint with revive
  .golangci.yaml
Labels: approved, cla: yes, lgtm, size/XS

#634 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#635 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#632 Deduplicate host matches to avoid excessive matches
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, kind/performance, lgtm, ok-to-test, size/L

#636 Set "disable-gateway-port-translation" label on local gateway Service
  config/203-local-gateway.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#640 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#642 Fix lint issue
  .github/workflows/knative-style.yaml
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/resources/gateway.go
Labels: approved, cla: yes, lgtm, size/XS

#643 Remove unused function ServiceNamespaceFromURL
  pkg/reconciler/ingress/resources/gateway.go
Labels: approved, cla: yes, lgtm, size/S

#647 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#649 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#650 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S
