Repository knative-extensions/net-istio, pull requests merged in 2021-06, with the labels that each got.

#651 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#652 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#653 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#655 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#654 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/clients.go
  vendor/knative.dev/networking/test/util.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#646 Remove unused configmaps in test/config
  test/config/config-autoscaler.yaml
  test/config/config-defaults.yaml
  test/config/config-features.yaml
  test/config/config-logging.yaml
Labels: approved, cla: yes, lgtm, size/M

#656 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#657 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#661 Update Knative dependency for release-0.23
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#659 delete the unused code
  pkg/reconciler/ingress/resources/gateway.go
Labels: approved, cla: yes, lgtm, size/XS

#660 No need to create HTTP server for wildcard gateway
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
Labels: approved, cla: yes, lgtm, size/M

#662 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#663 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#664 drop use of knative.dev/pkg/test.KubeClient
  test/e2e/clients.go
  test/e2e/probing_test.go
Labels: approved, cla: yes, lgtm, size/XS

#665 Bump k8s version in kind-e2e.yaml to v1.19, 1.20 and 1.21
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#668 Remove the unneeded code
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, lgtm, size/S

#670 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#671 Update comment about Gateway in configmap
  config/config.yaml
Labels: approved, cla: yes, lgtm, size/S

#673 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#674 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#675 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#648 Update Istio latest to 1.10.1 stable to 1.9.5
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  third_party/istio-stable/generate-manifests.sh
  third_party/istio-stable/istio-ci-mesh/istio.yaml
  third_party/istio-stable/istio-ci-no-mesh/istio.yaml
  third_party/istio-stable/istio-kind-mesh/istio.yaml
  third_party/istio-stable/istio-kind-no-mesh/istio.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#677 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#678 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#679 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#676 Do not patch local-gateway.mesh to config-istio
  third_party/istio-head/extra/config-istio-mesh.yaml
  third_party/istio-head/extra/configure-istio.sh
  third_party/istio-head/istio-ci-mesh/config-istio.yaml
  third_party/istio-head/istio-kind-mesh/config-istio.yaml
  third_party/istio-latest/extra/config-istio-mesh.yaml
  third_party/istio-latest/extra/configure-istio.sh
  third_party/istio-latest/istio-ci-mesh/config-istio.yaml
  third_party/istio-latest/istio-kind-mesh/config-istio.yaml
  third_party/istio-stable/extra/config-istio-mesh.yaml
  third_party/istio-stable/extra/configure-istio.sh
  third_party/istio-stable/istio-ci-mesh/config-istio.yaml
  third_party/istio-stable/istio-kind-mesh/config-istio.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#680 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#681 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#684 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#683 rename to be consistent with various net-* repos
  cmd/controller/main.go
  cmd/webhook/main.go
  config/400-webhook-peer-authentication.yaml
  config/500-mutating-webhook.yaml
  config/500-validating-webhook.yaml
  config/500-webhook-secret.yaml
  config/controller.yaml
  config/webhook-deployment.yaml
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/M

#682 Use terminationDrainDuration in MeshConfig.defaultConfig
  third_party/istio-head/istio-ci-mesh.yaml
  third_party/istio-head/istio-ci-no-mesh.yaml
  third_party/istio-head/istio-kind-mesh.yaml
  third_party/istio-head/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-mesh.yaml
  third_party/istio-latest/istio-kind-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  third_party/istio-stable/istio-ci-mesh.yaml
  third_party/istio-stable/istio-ci-mesh/istio.yaml
  third_party/istio-stable/istio-ci-no-mesh.yaml
  third_party/istio-stable/istio-ci-no-mesh/istio.yaml
  third_party/istio-stable/istio-kind-mesh.yaml
  third_party/istio-stable/istio-kind-mesh/istio.yaml
  third_party/istio-stable/istio-kind-no-mesh.yaml
  third_party/istio-stable/istio-kind-no-mesh/istio.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/L

#685 include v1 for admission review version
  config/500-mutating-webhook.yaml
  config/500-validating-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#686 fix webhook name
  config/webhook-service.yaml
Labels: approved, cla: yes, lgtm, size/XS

#687 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#688 [main] Upgrade to latest dependencies
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, cla: yes, lgtm, size/XS

#689 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#690 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#693 fix ordering of resources to ensure webhook config is last
  config/400-config-istio.yaml
  config/500-controller.yaml
  config/500-webhook-deployment.yaml
  config/500-webhook-service.yaml
  config/600-mutating-webhook.yaml
  config/600-validating-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS
