Repository knative-extensions/net-istio, pull requests merged in 2021-03, with the labels that each got.

#528 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/testing/clock.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#531 Consolidate lines in CODEOWNERS, drop hack/test
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/S

#529 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#534 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#535 Update Istio latest to 1.9.1.
  third_party/istio-latest/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#532 Handle the case when ingress name has dot
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
Labels: approved, cla: yes, lgtm, size/M

#536 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#537 Run all actions against main
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#547 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#544 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/istio/injection/client/client.go
  pkg/client/istio/injection/client/fake/fake.go
  vendor/knative.dev/networking/pkg/apis/networking/generic_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#548 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/client/client.go
  vendor/knative.dev/networking/pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#546 Add the reconciler machinery for pod addressability
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/serverlessservice/serverlessservice.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#545 Add a feature flag to guard pod addressability additions
  config/config.yaml
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/config/istio_test.go
Labels: approved, cla: yes, lgtm, size/M

#541 Use prefix matching for KIngress rule paths
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#550 Update Istio stable to 1.8.4.
  third_party/istio-stable/install-istio.sh
Labels: approved, cla: yes, lgtm, size/XS

#553 Add configuration for graceful shutdown to ingressgateways
  third_party/istio-head/istio-ci-mesh.yaml
  third_party/istio-head/istio-ci-no-mesh.yaml
  third_party/istio-head/istio-kind-mesh.yaml
  third_party/istio-head/istio-kind-no-mesh.yaml
  third_party/istio-head/istio-minimal.yaml
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-kind-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-minimal.yaml
  third_party/istio-stable/istio-ci-mesh.yaml
  third_party/istio-stable/istio-ci-no-mesh.yaml
  third_party/istio-stable/istio-kind-mesh.yaml
  third_party/istio-stable/istio-kind-no-mesh.yaml
  third_party/istio-stable/istio-minimal.yaml
Labels: approved, cla: yes, lgtm, size/M

#557 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#556 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#558 Add an accessor for DestinationRule objects
  pkg/reconciler/accessor/istio/destinationrule.go
  pkg/reconciler/accessor/istio/destinationrule_test.go
Labels: approved, cla: yes, lgtm, size/L

#559 Implement the SKS reconciler for pod addressability
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/serverlessservice/resources/destinationrule.go
  pkg/reconciler/serverlessservice/resources/virtualservice.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/L

#563 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#564 Start pod addressability reconciler with the controller
  cmd/controller/main.go
  config/200-clusterrole.yaml
  test/config/300-serverlessservice.yaml
Labels: approved, cla: yes, lgtm, size/M

#565 Replace copied networking CRDs with link to networking one
  hack/tools.go
  test/config/300-ingress.yaml
  test/config/300-serverlessservice.yaml
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/placeholder.go
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#567 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#572 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#570 Disable autoscaling for ingress gateways
  third_party/istio-head/istio-ci-mesh.yaml
  third_party/istio-head/istio-ci-no-mesh.yaml
  third_party/istio-head/istio-kind-mesh.yaml
  third_party/istio-head/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-kind-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-stable/istio-ci-mesh.yaml
  third_party/istio-stable/istio-ci-no-mesh.yaml
  third_party/istio-stable/istio-kind-mesh.yaml
  third_party/istio-stable/istio-kind-no-mesh.yaml
Labels: approved, cla: yes, kind/bug, lgtm, size/M

#571 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#574 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#576 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#577 Properly disable HPA for ingressgateways
  third_party/istio-head/istio-ci-mesh.yaml
  third_party/istio-head/istio-ci-no-mesh.yaml
  third_party/istio-head/istio-kind-mesh.yaml
  third_party/istio-head/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-kind-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-stable/istio-ci-mesh.yaml
  third_party/istio-stable/istio-ci-no-mesh.yaml
  third_party/istio-stable/istio-kind-mesh.yaml
  third_party/istio-stable/istio-kind-no-mesh.yaml
Labels: approved, cla: yes, lgtm, size/M

#578 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#579 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#580 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
