Repository knative-extensions/net-istio, pull requests merged in 2021-04, with the labels that each got.

#582 Use RunAndSyncInformers in all tests to ensure consistency
  pkg/reconciler/accessor/core/secret_test.go
  pkg/reconciler/accessor/istio/virtualservice_test.go
  pkg/reconciler/accessor/networking/certificate_test.go
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, size/S

#587 run e2e actions in release branches
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#588 [release-0.22] run e2e actions in release branches
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#592 Document that enable-virtualservice-status feature is experimental
  config/config.yaml
Labels: approved, cla: yes, kind/documentation, lgtm, size/XS

#593 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/network/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#596 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/state.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#594 Update istio manifest to make it simple
  go.sum
  third_party/istio-head/istio-ci-mesh.yaml
  third_party/istio-head/istio-ci-mesh/istio.yaml
  third_party/istio-head/istio-ci-no-mesh.yaml
  third_party/istio-head/istio-ci-no-mesh/istio.yaml
  third_party/istio-head/istio-kind-mesh.yaml
  third_party/istio-head/istio-kind-mesh/istio.yaml
  third_party/istio-head/istio-kind-no-mesh.yaml
  third_party/istio-head/istio-kind-no-mesh/istio.yaml
  third_party/istio-head/istio-minimal.yaml
  third_party/istio-head/istio-minimal/istio.yaml
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-mesh.yaml
  third_party/istio-latest/istio-kind-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  third_party/istio-latest/istio-minimal.yaml
  third_party/istio-latest/istio-minimal/istio.yaml
  third_party/istio-stable/istio-ci-mesh.yaml
  third_party/istio-stable/istio-ci-mesh/istio.yaml
  third_party/istio-stable/istio-ci-no-mesh.yaml
  third_party/istio-stable/istio-ci-no-mesh/istio.yaml
  third_party/istio-stable/istio-kind-mesh.yaml
  third_party/istio-stable/istio-kind-mesh/istio.yaml
  third_party/istio-stable/istio-kind-no-mesh.yaml
  third_party/istio-stable/istio-kind-no-mesh/istio.yaml
  third_party/istio-stable/istio-minimal.yaml
  third_party/istio-stable/istio-minimal/istio.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XXL

#595 install resources in a particular order
  third_party/istio-head/istio-ci-mesh/istio.yaml
  third_party/istio-head/istio-ci-no-mesh/istio.yaml
  third_party/istio-head/istio-kind-mesh/istio.yaml
  third_party/istio-head/istio-kind-no-mesh/istio.yaml
  third_party/istio-head/istio-minimal/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  third_party/istio-latest/istio-minimal/istio.yaml
  third_party/istio-stable/istio-ci-mesh/istio.yaml
  third_party/istio-stable/istio-ci-no-mesh/istio.yaml
  third_party/istio-stable/istio-kind-mesh/istio.yaml
  third_party/istio-stable/istio-kind-no-mesh/istio.yaml
  third_party/istio-stable/istio-minimal/istio.yaml
  third_party/library.sh
Labels: approved, cla: yes, lgtm, size/XXL

#599 Use SKS' PrivateServiceName field rather than generate it
  pkg/reconciler/serverlessservice/resources/destinationrule.go
  pkg/reconciler/serverlessservice/resources/virtualservice.go
  pkg/reconciler/serverlessservice/serverlessservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, cla: yes, lgtm, size/S

#597 Update istio stable to 1.9.1 and istio latest to 1.9.3, and add yq to vendors since it's needed for generating manifests
  go.mod
  go.sum
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  third_party/istio-latest/istio-minimal/istio.yaml
  third_party/istio-stable/generate-manifests.sh
  third_party/istio-stable/istio-ci-mesh/istio.yaml
  third_party/istio-stable/istio-ci-no-mesh/istio.yaml
  third_party/istio-stable/istio-kind-mesh/istio.yaml
  third_party/istio-stable/istio-kind-no-mesh/istio.yaml
  third_party/istio-stable/istio-minimal/istio.yaml
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#603 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#605 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#606 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#608 drop ignore-unknown-comments
  third_party/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#610 Drop --strict flag on ko
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#609 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#612 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm

#611 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#614 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#616 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#617 [istio-stable] renable global mTLS when in mesh mode
  third_party/istio-stable/extra/istio-mesh.yaml
  third_party/istio-stable/generate-manifests.sh
  third_party/istio-stable/istio-ci-mesh/istio.yaml
  third_party/istio-stable/istio-kind-mesh/istio.yaml
Labels: approved, cla: yes, lgtm, size/M
