Repository knative-extensions/net-istio, pull requests merged in 2021-10, with the labels that each got.

#778 Reverting coc changes
  CODE-OF-CONDUCT.md
  code-of-conduct.md
Labels: approved, lgtm, cla: yes, size/M

#780 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#787 fix go1.17 related issues
  .github/workflows/kind-e2e.yaml
  pkg/defaults/zz_generated.deepcopy.go
  pkg/reconciler/ingress/config/zz_generated.deepcopy.go
  test/upload-test-images.sh
Labels: approved, lgtm, size/S, cla: yes
