Repository knative-extensions/net-istio, pull requests merged in 2022-05, with the labels that each got.

#915 Remove `local-gateway.mesh: "mesh"` option
  config/400-config-istio.yaml
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/config/istio_test.go
  pkg/reconciler/ingress/config/testdata/config-istio.yaml
Labels: approved, lgtm, size/M

#916 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#917 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#919 Bump kind version to 0.12.0 for k8s 1.23
  .github/workflows/kind-e2e.yaml
Labels: size/XS, approved, lgtm

#921 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#922 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#923 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#910 Add doc how to update Istio manifest
  ISTIO.md
  hack/update-codegen.sh
Labels: approved, lgtm, size/M

#925 bump istio manifests to 1.13.3
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/S, kind/cleanup

#926 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#929 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#927 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/golang-lru/lru.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/config/doc.go
  vendor/knative.dev/networking/pkg/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/constants.go
  vendor/knative.dev/networking/pkg/http/error.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/http/probe/handler.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/knative.dev/networking/pkg/labels/labels.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/main.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/networking/test/test_images/retry/main.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/networking/test/test_images/timeout/timeout.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#920 Add filtering support for secret informer in ingress controller
  cmd/controller/main.go
  config/500-controller.yaml
  pkg/reconciler/informerfiltering/util.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/filtered/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/filtered/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/filtered_factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, kind/enhancement

#933 Fix net deprecations
  pkg/reconciler/ingress/config/store.go
  pkg/reconciler/ingress/config/store_test.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/serverlessservice/resources/virtualservice.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
Labels: approved, lgtm, size/M

#931 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/labels/labels.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
