Repository knative-extensions/net-istio, pull requests merged in 2022-02, with the labels that each got.

#856 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: size/XS, approved, lgtm

#858 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#855 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#860 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#859 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: approved, lgtm, size/M

#862 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#861 Updates webhook to use app.kubernetes.io selector label
  config/600-validating-webhook.yaml
Labels: size/XS, approved, lgtm

#863 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#865 Bump Istio to 1.12.2
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/M

#866 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#868 Updates val webhook selector to reduce invocations
  config/600-validating-webhook.yaml
Labels: size/XS, approved, lgtm, kind/cleanup

#872 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/S

#873 Bump Istio 1.13.0
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, size/XXL, lgtm

#875 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#876 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, approved, lgtm

#877 update ytt package name
  third_party/library.sh
Labels: size/XS, approved, lgtm

#878 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
