Repository knative-extensions/net-istio, pull requests merged in 2022-12, with the labels that each got.

#1026 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1031 [release-1.8] Rebuild using Go 1.19.4 (to address CVEs)
  go.mod
Labels: size/XS, approved, lgtm

#1033 [release-1.6] Rebuild using Go 1.19.4 (to address CVEs)
  go.mod
Labels: size/XS, approved, lgtm

#1032 [release-1.7] Rebuild using Go 1.19.4 (to address CVEs)
  go.mod
Labels: size/XS, approved, lgtm

#1035 [release-1.7] gofmt with go1.19
  pkg/client/istio/clientset/versioned/fake/register.go
  pkg/client/istio/clientset/versioned/scheme/register.go
  pkg/reconciler/ingress/doc.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  test/e2e/clients.go
Labels: approved, lgtm, size/S

#1036 [release-1.6] gofmt with go1.19
  pkg/client/istio/clientset/versioned/fake/register.go
  pkg/client/istio/clientset/versioned/scheme/register.go
  pkg/reconciler/ingress/doc.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  test/e2e/clients.go
Labels: approved, lgtm, size/S

#1034 [release-1.8] gofmt go1.19
  pkg/client/istio/clientset/versioned/fake/register.go
  pkg/client/istio/clientset/versioned/scheme/register.go
  pkg/reconciler/ingress/doc.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  test/e2e/clients.go
Labels: approved, lgtm, size/S

#1037 [release-1.6] fix release script
  hack/release.sh
Labels: size/XS, approved, lgtm

#1038 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1040 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
