Repository knative-extensions/net-istio, pull requests merged in 2022-08, with the labels that each got.

#960 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/networking/test/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#963 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#964 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#965 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#966 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#967 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#969 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#968 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#970 bump istio manifests to 1.14.3
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/L, kind/enhancement

#971 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#972 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
