Repository knative-extensions/net-istio, pull requests merged in 2022-10, with the labels that each got.

#988 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#991 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#992 Bump k8s version in kind
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/S

#994 Add workaround for k8s 1.25
  .github/workflows/kind-e2e.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  third_party/library.sh
Labels: approved, lgtm, size/S

#1001 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1004 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
