Repository knative-extensions/net-istio, pull requests merged in 2022-04, with the labels that each got.

#899 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#895 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, size/M

#903 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#900 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/L

#904 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#905 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#906 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/S

#907 Bump k8s version in KinD
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/S

#901 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#908 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#909 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#911 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#912 Update Istio version to 1.13.2
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/S, ok-to-test, kind/cleanup

#914 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
