Repository knative-extensions/net-istio, pull requests merged in 2022-06, with the labels that each got.

#936 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#937 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#939 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#941 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#943 bump kind and k8s versions for kind-e2e test
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/S

#946 bump istio manifests to 1.14.1
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, size/XXL, lgtm, kind/enhancement

#948 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review
