Repository knative-extensions/net-istio, pull requests merged in 2022-03, with the labels that each got.

#885 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#880 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/S

#884 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/main.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/networking/test/test_images/retry/main.go
  vendor/knative.dev/networking/test/test_images/runtime/main.go
  vendor/knative.dev/networking/test/test_images/timeout/timeout.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/knative.dev/networking/test/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#886 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#891 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#893 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#894 Removing deprecated serving.knative.dev/release label
  config/200-clusterrole.yaml
  config/202-gateway.yaml
  config/203-local-gateway.yaml
  config/400-config-istio.yaml
  config/400-webhook-peer-authentication.yaml
  config/500-controller.yaml
  config/500-webhook-deployment.yaml
  config/500-webhook-secret.yaml
  config/500-webhook-service.yaml
  config/600-mutating-webhook.yaml
  config/600-validating-webhook.yaml
  hack/release.sh
  pkg/reconciler/ingress/config/testdata/config-istio.yaml
  pkg/reconciler/ingress/config/testdata/config-network.yaml
  test/config/200-service-account.yaml
  test/config/chaosduck.yaml
Labels: approved, lgtm, size/M

#896 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#897 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/XL
