Repository knative-extensions/net-istio, pull requests merged in 2022-09, with the labels that each got.

#974 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#976 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/interface.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#978 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/configmap/load.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#980 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#982 bump istio manifests to 1.15.0
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, size/XXL, lgtm, kind/enhancement

#983 Fix psp in config manifests
  config/500-controller.yaml
  config/500-webhook-deployment.yaml
Labels: approved, lgtm, size/S

#981 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#986 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#987 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
