Repository knative-extensions/net-istio, pull requests merged in 2023-03, with the labels that each got.

#1071 [release-1.8] trigger to build release with go1.19.6
  go.mod
Labels: size/XS, approved, lgtm

#1072 [release-1.9] trigger to build release with go1.19.6
  go.mod
Labels: size/XS, approved, lgtm

#1073 [release-1.8] bump istio to v1.15.6
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/M

#1074 [release-1.9] bump istio to v1.16.3
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/M

#1075 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1077 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1068 bump istio to v1.17.1
  test/config/config-logging.yaml
  test/e2e-tests.sh
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/L

#1078 Drop access logging & unneeded patches
  third_party/istio-latest/istio-ci-mesh.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  third_party/library.sh
  third_party/upgrade-resource-versions.ytt.yaml
Labels: approved, lgtm, size/S

#1076 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1079 disable telemetry in e2e tests
  test/e2e-tests.sh
Labels: size/XS, approved, lgtm

#1081 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1083 [main] Upgrade to latest dependencies
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: size/XS, approved, lgtm

#1084 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
