Repository knative-extensions/net-istio, pull requests merged in 2023-01, with the labels that each got.

#1045 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1047 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1041 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1042 Ensure that a Gateway name does not exceed 63 length
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
Labels: approved, lgtm, size/M, ok-to-test, kind/bug

#1043 Ensure that a Secret label value does not exceed 63 length
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
Labels: approved, lgtm, size/L, ok-to-test, kind/bug

#1046 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, approved, skip-review

#1048 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm
