Repository knative-extensions/net-istio, pull requests merged in 2023-10, with the labels that each got.

#1182 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1185 [release-1.10] Rebuild using Go 1.20.10 (to address CVEs)
  go.mod
Labels: size/XS, approved, lgtm

#1189 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1192 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1193 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1194 Bump Istio to 1.19.3
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/M

#1085 Add support for `system-internal-tls` in net-istio
  .github/workflows/kind-e2e.yaml
  DEVELOPMENT.md
  cmd/controller/main.go
  config/700-istio-secret.yaml
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/destinationrule.go
  pkg/reconciler/ingress/resources/destinationrule_test.go
  test/config/system-internal-tls/config-network.yaml
  test/generate-upstream-cert.sh
  vendor/knative.dev/networking/pkg/certificates/certs.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/certificates/key_pair.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/enhancement

#1195 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1198 Use curl instead of wget
  third_party/library.sh
Labels: size/XS, approved, lgtm

#1197 drop unused flag during codegen
  hack/update-codegen.sh
Labels: size/XS, approved, lgtm

#1199 Shorten kind/e2e GitHub Action Names
  .github/workflows/kind-e2e.yaml
Labels: size/XS, approved, lgtm

#1196 Bump Istio Client Libs to v1.19.3
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/go-openapi/jsonreference/internal/normalize_url.go
  vendor/istio.io/api/analysis/v1alpha1/message.pb.go
  vendor/istio.io/api/label/labels.pb.html
  vendor/istio.io/api/meta/v1alpha1/status.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.gen.json
  vendor/istio.io/api/networking/v1beta1/destination_rule.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.proto
  vendor/istio.io/api/networking/v1beta1/gateway.gen.json
  vendor/istio.io/api/networking/v1beta1/gateway.pb.go
  vendor/istio.io/api/networking/v1beta1/gateway.proto
  vendor/istio.io/api/networking/v1beta1/proxy_config.pb.go
  vendor/istio.io/api/networking/v1beta1/service_entry.gen.json
  vendor/istio.io/api/networking/v1beta1/service_entry.pb.go
  vendor/istio.io/api/networking/v1beta1/sidecar.gen.json
  vendor/istio.io/api/networking/v1beta1/sidecar.pb.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.gen.json
  vendor/istio.io/api/networking/v1beta1/virtual_service.pb.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.proto
  vendor/istio.io/api/networking/v1beta1/virtual_service_deepcopy.gen.go
  vendor/istio.io/api/networking/v1beta1/virtual_service_json.gen.go
  vendor/istio.io/api/networking/v1beta1/workload_entry.gen.json
  vendor/istio.io/api/networking/v1beta1/workload_entry.pb.go
  vendor/istio.io/api/networking/v1beta1/workload_entry.proto
  vendor/istio.io/api/networking/v1beta1/workload_group.gen.json
  vendor/istio.io/api/networking/v1beta1/workload_group.pb.go
  vendor/istio.io/api/networking/v1beta1/workload_group.pb.html
  vendor/istio.io/api/networking/v1beta1/workload_group.proto
  vendor/istio.io/api/type/v1beta1/selector.pb.go
  vendor/k8s.io/klog/v2/format.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1200 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1201 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1202 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1203 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1204 [release-1.11] bump to latest istio patch release
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/M

#1205 [release-1.10] bump to latest istio patch release
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/M
