Repository knative-extensions/net-istio, pull requests merged in 2023-07, with the labels that each got.

#1140 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1141 Drop PeerAuthentication for domainmapping-webhook
  config/400-webhook-peer-authentication.yaml
Labels: approved, lgtm, size/S

#1143 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1142 chore: Migrate to sets.Set[string] when possible
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, lgtm, size/L, ok-to-test, kind/cleanup
