Repository knative-extensions/net-istio, pull requests merged in 2023-02, with the labels that each got.

#1051 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1052 Use serving-writers and reviewers teams
  OWNERS
Labels: size/XS, approved, lgtm

#1053 Drop Istio HEAD
  ISTIO.md
  hack/update-codegen.sh
  third_party/istio-head/README.md
  third_party/istio-head/extra/istio-mesh.yaml
  third_party/istio-head/generate-manifests.sh
  third_party/istio-head/install-istio.sh
  third_party/istio-head/istio-ci-mesh.yaml
  third_party/istio-head/istio-ci-mesh/istio.yaml
  third_party/istio-head/istio-ci-no-mesh.yaml
  third_party/istio-head/istio-ci-no-mesh/istio.yaml
  third_party/istio-head/istio-kind-no-mesh.yaml
  third_party/istio-head/istio-kind-no-mesh/istio.yaml
Labels: approved, size/XXL, lgtm

#1055 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#1057 Ensure wildcard certificate secrets can also track back their source secret
  pkg/reconciler/accessor/core/secret.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
Labels: approved, lgtm, size/S, needs-ok-to-test, kind/bug

#1056 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1059 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1060 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1062 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1064 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1065 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
