Repository knative-extensions/net-istio, pull requests merged in 2023-06, with the labels that each got.

#1125 remove enable-virtualservice-status config
  config/400-config-istio.yaml
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/config/istio_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, lgtm, size/L, kind/cleanup, kind/api-change

#1126 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1127 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_defaults.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/main.go
  vendor/knative.dev/networking/test/test_images/retry/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1128 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1131 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/options.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1132 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1134 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1133 Add ambient profile
  .github/workflows/kind-e2e.yaml
  test/config/100-serving-namespace.yaml
  test/config/100-test-namespace.yaml
  third_party/istio-latest/istio-ci-ambient.yaml
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-kind-ambient.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/library.sh
Labels: approved, size/XXL, lgtm

#1136 Drop NodePort from kind manifests
  third_party/istio-latest/istio-kind-ambient.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: size/XS, approved, lgtm

#1138 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
