Repository knative-extensions/net-istio, pull requests merged in 2023-11, with the labels that each got.

#1206 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1208 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/gorilla/websocket/.editorconfig
  vendor/github.com/gorilla/websocket/.gitignore
  vendor/github.com/gorilla/websocket/.golangci.yml
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/Makefile
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/tls_handshake.go
  vendor/github.com/gorilla/websocket/tls_handshake_116.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/dial.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1209 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1211 Bump Istio to 1.20.0
  go.mod
  go.sum
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  vendor/istio.io/api/analysis/v1alpha1/message.gen.json
  vendor/istio.io/api/meta/v1alpha1/status.gen.json
  vendor/istio.io/api/meta/v1alpha1/status.pb.html
  vendor/istio.io/api/networking/v1beta1/destination_rule.gen.json
  vendor/istio.io/api/networking/v1beta1/destination_rule.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.proto
  vendor/istio.io/api/networking/v1beta1/gateway.gen.json
  vendor/istio.io/api/networking/v1beta1/gateway.pb.go
  vendor/istio.io/api/networking/v1beta1/gateway.proto
  vendor/istio.io/api/networking/v1beta1/proxy_config.gen.json
  vendor/istio.io/api/networking/v1beta1/service_entry.gen.json
  vendor/istio.io/api/networking/v1beta1/service_entry.pb.go
  vendor/istio.io/api/networking/v1beta1/service_entry.proto
  vendor/istio.io/api/networking/v1beta1/sidecar.gen.json
  vendor/istio.io/api/networking/v1beta1/sidecar.pb.go
  vendor/istio.io/api/networking/v1beta1/sidecar.proto
  vendor/istio.io/api/networking/v1beta1/sidecar_deepcopy.gen.go
  vendor/istio.io/api/networking/v1beta1/sidecar_json.gen.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.gen.json
  vendor/istio.io/api/networking/v1beta1/virtual_service.pb.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.proto
  vendor/istio.io/api/networking/v1beta1/workload_entry.gen.json
  vendor/istio.io/api/networking/v1beta1/workload_group.gen.json
  vendor/istio.io/api/type/v1beta1/selector.gen.json
  vendor/istio.io/api/type/v1beta1/selector.pb.go
  vendor/istio.io/api/type/v1beta1/selector.pb.html
  vendor/istio.io/api/type/v1beta1/selector.proto
  vendor/istio.io/api/type/v1beta1/selector_deepcopy.gen.go
  vendor/istio.io/api/type/v1beta1/selector_json.gen.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1213 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, approved, lgtm

#1214 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_helpers.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1219 Drop testing on k8s v1.26
  .github/workflows/kind-e2e.yaml
Labels: size/XS, approved, lgtm

#1220 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1216 Filter IngressTLS for visibility IngressVisibilityExternalIP
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
Labels: approved, lgtm, size/M
