Repository knative-extensions/net-istio, pull requests merged in 2023-05, with the labels that each got.

#1106 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1105 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1109 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1108 Check all host names of a certificate in isWildcardSecret
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
  pkg/reconciler/ingress/resources/util.go
Labels: approved, lgtm, size/M, ok-to-test, kind/bug

#1111 Bump kind version
  .github/workflows/kind-e2e.yaml
Labels: size/XS, approved, lgtm

#1113 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1112 Disable update test
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#1115 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1116 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1117 drop safe-to-evict annotations
  config/500-controller.yaml
  config/500-webhook-deployment.yaml
Labels: size/XS, approved, lgtm

#1118 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
