Repository knative-extensions/net-istio, pull requests merged in 2023-04, with the labels that each got.

#1086 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1089 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1082 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, size/S, skip-review

#1092 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1090 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1091 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#1096 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#1093 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1097 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1100 Fixing golangci-lint issues
  cmd/webhook/main.go
  pkg/defaults/deployment_defaults.go
  pkg/reconciler/accessor/core/secret.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister_test.go
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
  test/e2e/clients.go
  test/e2e/e2e.go
Labels: approved, lgtm, size/L, kind/cleanup

#1098 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1101 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#1095 Add missing probes
  cmd/webhook/main.go
  config/500-controller.yaml
  config/500-webhook-deployment.yaml
Labels: approved, lgtm, size/M

#1102 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1104 Bump k8s version on github action
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/M
