Repository knative-extensions/net-istio, pull requests merged in 2024-03, with the labels that each got.

#1281 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1282 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/test/e2e-common.sh
  vendor/knative.dev/networking/test/e2e-tests.sh
  vendor/knative.dev/networking/test/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1283 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1285 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1286 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1287 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1288 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/jsonpb/decode.go
  vendor/github.com/golang/protobuf/jsonpb/encode.go
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/google.golang.org/genproto/LICENSE
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/google.golang.org/genproto/googleapis/api/tidyfix.go
  vendor/google.golang.org/genproto/internal/doc.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1289 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1290 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1293 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1294 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1295 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1250 Feat/gateway filtering
  go.mod
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/config/istio_test.go
  pkg/reconciler/ingress/config/zz_generated.deepcopy.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
  test/e2e/exposition_test.go
Labels: approved, size/XXL, lgtm, ok-to-test

#1296 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/SECURITY.md
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1298 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/modules.txt
Labels: approved, lgtm, size/S
