Repository knative-extensions/net-istio, pull requests merged in 2024-01, with the labels that each got.

#1230 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1232 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, skip-review

#1233 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/kflag/set.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1235 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1236 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1242 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1241 Add K8s 1.29 testing and bump github actions
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/S

#1240 [release-1.11] bump istio to v1.18.7
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/L

#1237 Bump Istio to v1.20.2
  go.mod
  go.sum
  hack/update-k8s-deps.sh
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  vendor/istio.io/api/networking/v1beta1/destination_rule.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.proto
  vendor/istio.io/api/networking/v1beta1/gateway.pb.go
  vendor/istio.io/api/networking/v1beta1/gateway.proto
  vendor/istio.io/api/type/v1beta1/selector.pb.go
  vendor/istio.io/api/type/v1beta1/selector.pb.html
  vendor/istio.io/api/type/v1beta1/selector.proto
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1239 [release-1.12] bump istio v1.19.6
  go.mod
  go.sum
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1244 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1245 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1246 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1251 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/context.go
  vendor/github.com/go-logr/logr/context_noslog.go
  vendor/github.com/go-logr/logr/context_slog.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/logr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr.go
  vendor/github.com/go-logr/logr/slogsink.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/version7.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1252 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_others.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_windows.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1253 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/certificates/certs.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/certificates/key_pair.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
