Repository knative-extensions/net-istio, pull requests merged in 2024-02, with the labels that each got.

#1254 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1228 Host cluster-local-domain-tls on cluster-local gateway with SNI
  config/203-local-gateway.yaml
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
Labels: approved, lgtm, size/XL, kind/enhancement

#1249 feat: New istio config format
  go.mod
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/config/istio_test.go
Labels: approved, lgtm, size/L, ok-to-test, kind/enhancement

#1257 docs: Add documentation about the new config format (#1247)
  config/400-config-istio.yaml
Labels: approved, lgtm, size/M, ok-to-test

#1259 docs: Fix description if old & new format are defined
  config/400-config-istio.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test, kind/documentation

#1260 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1261 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1262 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1263 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1265 drop k8s 1.27 from kind testing
  .github/workflows/kind-e2e.yaml
Labels: size/XS, approved, lgtm

#1264 docs: Update net-istio configmap documentation (#1248)
  config/400-config-istio.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test, kind/documentation

#1266 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1267 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1270 bump e2e cluster version to 1.28
  test/e2e-tests.sh
Labels: size/XS, approved, lgtm

#1272 use knative/actions/setup-go and drop periodic testing
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/M

#1274 [release-1.12] bump istio to v1.19.7
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/M

#1273 bump istio to v1.20.3
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
Labels: approved, lgtm, size/M

#1276 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1277 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/LICENSE
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1278 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_domain.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_networking_client.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_realm.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/generated_expansion.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/networking_client.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/interface.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/expansion_generated.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/realm.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
