Repository knative-extensions/net-istio, pull requests merged in 2024-12, with the labels that each got.

#1386 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1389 Pin Chainguard version
  .github/workflows/kind-e2e.yaml
Labels: size/XS, approved, lgtm

#1388 Bump Kind and k8s version
  .github/workflows/kind-e2e.yaml
  test/e2e-tests.sh
Labels: size/XS, approved, lgtm

#1390 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1387 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
