Repository knative-extensions/net-istio, pull requests merged in 2024-07, with the labels that each got.

#1340 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1342 fix boilerplate
  config/placeholder.go
  pkg/reconciler/accessor/core/secret.go
  pkg/reconciler/accessor/core/secret_test.go
  pkg/reconciler/accessor/errors.go
  pkg/reconciler/accessor/errors_test.go
  pkg/reconciler/accessor/istio/destinationrule.go
  pkg/reconciler/accessor/istio/destinationrule_test.go
  pkg/reconciler/accessor/istio/virtualservice.go
  pkg/reconciler/accessor/istio/virtualservice_test.go
  pkg/reconciler/accessor/networking/certificate.go
  pkg/reconciler/accessor/networking/certificate_test.go
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/config/istio_test.go
  pkg/reconciler/ingress/config/store.go
  pkg/reconciler/ingress/config/store_test.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/names/doc.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
  pkg/reconciler/serverlessservice/serverlessservice_test.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/upload-test-images.sh
Labels: approved, lgtm, size/M

#1341 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_asm.go
  vendor/github.com/cespare/xxhash/v2/xxhash_other.go
  vendor/github.com/cespare/xxhash/v2/xxhash_safe.go
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirst.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand_go1.21.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/dns/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1344 Revert https://github.com/knative-extensions/net-istio/pull/1085
  .github/workflows/kind-e2e.yaml
  DEVELOPMENT.md
  cmd/controller/main.go
  config/700-istio-knative-certificate.yaml
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/destinationrule.go
  pkg/reconciler/ingress/resources/destinationrule_test.go
  test/config/system-internal-tls/config-network.yaml
  test/generate-upstream-cert.sh
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1346 Remove useless if
  pkg/reconciler/ingress/resources/gateway.go
Labels: size/XS, approved, lgtm, ok-to-test, kind/cleanup

#1347 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1349 preserve appropriate header matches when creating the virtualservice
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
Labels: approved, lgtm, size/S

#1353 Use a different 'static' image that supports s390x and ppc
  .ko.yaml
Labels: size/XS, approved, lgtm

#1356 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
