Repository knative-extensions/net-istio, pull requests merged in 2024-06, with the labels that each got.

#1331 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/genproto/googleapis/api/annotations/annotations.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/http.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/resource.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/routing.pb.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/google.golang.org/genproto/googleapis/api/launch_stage.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1332 use cgr.dev/chainguard/static:latest which is nonroot
  .ko.yaml
Labels: size/XS, approved, lgtm

#1333 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1334 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1335 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1336 bump istio to v1.22.1
  go.mod
  go.sum
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  vendor/istio.io/api/analysis/v1alpha1/message.pb.go
  vendor/istio.io/api/meta/v1alpha1/status.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.proto
  vendor/istio.io/api/networking/v1beta1/gateway.pb.go
  vendor/istio.io/api/networking/v1beta1/gateway.proto
  vendor/istio.io/api/networking/v1beta1/proxy_config.pb.go
  vendor/istio.io/api/networking/v1beta1/proxy_config.pb.html
  vendor/istio.io/api/networking/v1beta1/proxy_config.proto
  vendor/istio.io/api/networking/v1beta1/service_entry.pb.go
  vendor/istio.io/api/networking/v1beta1/service_entry.proto
  vendor/istio.io/api/networking/v1beta1/sidecar.pb.go
  vendor/istio.io/api/networking/v1beta1/sidecar.proto
  vendor/istio.io/api/networking/v1beta1/virtual_service.pb.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.proto
  vendor/istio.io/api/networking/v1beta1/workload_entry.pb.go
  vendor/istio.io/api/networking/v1beta1/workload_entry.proto
  vendor/istio.io/api/networking/v1beta1/workload_group.pb.go
  vendor/istio.io/api/networking/v1beta1/workload_group.proto
  vendor/istio.io/api/type/v1beta1/selector.pb.go
  vendor/istio.io/api/type/v1beta1/selector.pb.html
  vendor/istio.io/api/type/v1beta1/selector.proto
  vendor/istio.io/client-go/pkg/apis/networking/v1beta1/types.gen.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1337 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1338 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/convert.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1339 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/kind2resource.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/filter.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/format-code.sh
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
