Repository knative-extensions/net-istio, pull requests merged in 2024-04, with the labels that each got.

#1299 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1300 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1301 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1302 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1303 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1304 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/httpoption.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/update.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1305 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/ingress.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/networking/test/test_images/runtime/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1306 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1309 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1308 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/networking/test/conformance/ingress/update.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1310 bump istio to v1.21.1
  go.mod
  go.sum
  third_party/istio-latest/generate-manifests.sh
  third_party/istio-latest/istio-ci-ambient/istio.yaml
  third_party/istio-latest/istio-ci-mesh/istio.yaml
  third_party/istio-latest/istio-ci-no-mesh/istio.yaml
  third_party/istio-latest/istio-kind-ambient/istio.yaml
  third_party/istio-latest/istio-kind-no-mesh/istio.yaml
  vendor/istio.io/api/LICENSE
  vendor/istio.io/api/analysis/v1alpha1/message.pb.go
  vendor/istio.io/api/label/labels.pb.html
  vendor/istio.io/api/meta/v1alpha1/status.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.pb.go
  vendor/istio.io/api/networking/v1beta1/destination_rule.proto
  vendor/istio.io/api/networking/v1beta1/destination_rule_deepcopy.gen.go
  vendor/istio.io/api/networking/v1beta1/destination_rule_json.gen.go
  vendor/istio.io/api/networking/v1beta1/gateway.pb.go
  vendor/istio.io/api/networking/v1beta1/proxy_config.pb.go
  vendor/istio.io/api/networking/v1beta1/service_entry.pb.go
  vendor/istio.io/api/networking/v1beta1/sidecar.pb.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.pb.go
  vendor/istio.io/api/networking/v1beta1/virtual_service.proto
  vendor/istio.io/api/networking/v1beta1/workload_entry.pb.go
  vendor/istio.io/api/networking/v1beta1/workload_group.pb.go
  vendor/istio.io/api/type/v1beta1/selector.pb.go
  vendor/istio.io/client-go/LICENSE
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1311 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1312 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1314 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
