Repository knative-extensions/net-istio, pull requests merged in 2025-04, with the labels that each got.

#1420 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1422 bump to golangci yaml v2
  .golangci.yaml
Labels: size/XS, approved, lgtm

#1423 update golangci lint
  .golangci.yaml
Labels: approved, lgtm, size/L

#1426 increase test coverage
  .codecov.yaml
  pkg/reconciler/serverlessservice/resources/destinationrule_test.go
  pkg/reconciler/serverlessservice/resources/virtualservice_test.go
Labels: approved, lgtm, size/L

#1425 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1424 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/types/typeutil/callee.go
  vendor/golang.org/x/tools/internal/event/label/label.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/modindex/lookup.go
  vendor/golang.org/x/tools/internal/pkgbits/decoder.go
  vendor/golang.org/x/tools/internal/stdlib/deps.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/typeparams/free.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/golang.org/x/tools/internal/typesinternal/classify_call.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1429 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
