Repository knative-extensions/net-istio, pull requests merged in 2025-01, with the labels that each got.

#1391 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1393 update linter config and fix issues
  .golangci.yaml
  pkg/defaults/deployment_defaults_test.go
  pkg/reconciler/accessor/core/secret_test.go
  pkg/reconciler/accessor/istio/destinationrule.go
  pkg/reconciler/accessor/istio/virtualservice.go
  pkg/reconciler/accessor/istio/virtualservice_test.go
  pkg/reconciler/accessor/networking/certificate.go
  pkg/reconciler/accessor/networking/certificate_test.go
  pkg/reconciler/ingress/config/istio.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
  pkg/reconciler/ingress/resources/gateway.go
  pkg/reconciler/ingress/resources/gateway_test.go
  pkg/reconciler/ingress/resources/secret.go
  pkg/reconciler/ingress/resources/secret_test.go
  pkg/reconciler/ingress/resources/virtual_service.go
  pkg/reconciler/ingress/resources/virtual_service_test.go
  pkg/reconciler/serverlessservice/controller.go
  pkg/reconciler/testing/factory.go
  test/conformance/ingress_test.go
  test/e2e/probing_test.go
Labels: approved, lgtm, size/L

#1396 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1400 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1398 fix nightly build
  test/e2e-common.sh
Labels: size/XS, approved, lgtm

#1402 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1404 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1406 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1405 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/README.md
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/internal/flags/flags.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map_go111.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map_go112.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/convert_map.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XL
